### ISSUE TITLE
Issue with AGS 2.0.1

### ISSUE THREAD

**Issue by jpachecoxyz** [nine7nine/n7n-AGS-Shell#2]
in the last AGS version I guess the dev change some in the config files:
This is the error that I encounter when try to run AGS within your ags config

`tip: valid names are:  "app.js" "app.ts" "app.jsx" "app.tsx"`

Im going to changes the names of files, and try to change som variables names because of the file names that I'll change.

**Comment by nine7nine** [comment]
So i'm a bit MIA, atm. My semi-new job has been taking up a lot of my time, so i currently haven't even updated my own system in a bit, let alone work on my own pet projects.

If you happen to fix the issues you've encountered feel free to submit a PR. I'll have a look and likely pull it, once i can test it.... 

Also, just an fyi, Aylur isn't making his dotfiles public anymore -- so while i can go back and pick up some bugfixes and other changes, in the long term i may end up finding a shell based on his new libraries/frameworks...

We shall see.

**Comment by nine7nine** [comment]
So, I just updated my Arch system after a few months (huuuge amount of updates)... My shell still works fine, given that I hold back hyprland and AGS packages (this avoids my desktop ever breaking).

this shell will never work on AGS 2.x, according to Aylur: I basically would need to rebuild it from scratch: https://github.com/Aylur/ags/commit/f608c6695b7829095bc5bd07a3b45616d60b3b3d#diff-fb33adb4b4492173d6ebacb0accb01f3285903b56d5506c5d96ea5ea0c7518d2

So. you can just use AGSv1 + my shell for now (as I likely will). I am going to be looking at creating a new shell based on AGSv2 - but this will take some time...

In the meantime, I will update all of my hyprland packages / plugins and fix any breakage with that. I haven't updated hyprland since august ( just too busy at work, so outside of work -- basically haven't touched a computer, given I am doing heavy lifting on workstations/servers all day long, everyday)...

that all aside: creating something new like this shell for AGSv2 - probably since going to be all that hard. As is, i shifted away from many of Aylur's components in my shell (including it not managing hyprland configs), so it's really just a panel, some widgets + hyprland plugin.... When I have some time off or free time, I'll start looking at creating some new, but very similar based on AGSv2.

**Comment by jpachecoxyz** [comment]
Got it, Im going to downgrade AGS, in the meaning of the time I'm going to try to update your Ags shell to AGS v2.x, but im not promise nothing , my job is a life sucker too.

**Comment by nine7nine** [comment]
no worries - I wasn't expecting anything! ~ Just letting you know where things stand.

That said: i still do need to update hyprland, so I expect the workspace switcher is likely borked on the latest hyprland. Anyway, I expect I will update hyprland and fix any breakage in the next day or two.

Ah, it's not that my job is a life sucker -- I absolutely love my job. It's just that I work fully-remote at an MSP: so when I finish work, the last thing i feel like doing is tinkering around on a computer. haha

**Comment by jpachecoxyz** [comment]
I was using the flake version of AGS, NixOS point to the latest version from github that is V2.x.x, the unstable an stable version without using the flake is V1.8.x, So now is working, Im going to lock that AGS version from now on. Thanks for your time.

![image](https://github.com/user-attachments/assets/0b531eea-e874-4931-8f81-2c5caf16b512)
